app/blueprints/__init__.py
from .home import home
from .upload_api import upload_api

app/blueprints/home/__init__.py
from .blueprint import home

app/blueprints/home/blueprint.py
from flask import Blueprint, render_template, request, Response
import cv2, time, os, base64
from models import products, cropped
from middlewares.yolo import detect, VideoCamera
from middlewares.knn import get_neighbors
import pandas as pd
import pickle

home = Blueprint('home', __name__)
path = os.path.dirname(os.path.abspath(__file__))
ptuf = os.path.join(path, "../../static/images")


@home.route('/video', methods=["GET","POST"])
def video():
    if request.method == "POST":
        print(request)
        _ = VideoCamera().get_frame(capture = True)

        categoryPredict = detect('static/images/object-detection.jpg')

        if len(categoryPredict) > 0:
            croppedDectection = []
            for i in range(len(categoryPredict)):
                croppedDectection.append('images/cropped-dectecion-{}.jpg'.format(i))

            croppedObject = cropped.list_object(zip(categoryPredict, croppedDectection))
        else: 
            croppedObject = None

        return render_template('home.html',f='static/images/object-detection.jpg', c=croppedObject)
    
    return render_template('home.html', f = None, c = [])

def gen(camera):
    while True:
        frame = camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')


@home.route('/video_feed')
def videoFeed():
    return Response(gen(VideoCamera()),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

@home.route("/still", methods=["GET","POST"])
def still():
    if request.method == "POST":
        f = request.files["uploadfile"]
        
        _, ext = os.path.splitext(f.filename)
        if os.path.exists(os.path.join(ptuf,"input"+ ext)):
            os.remove(os.path.join(ptuf,"input" + ext))

        f.save(os.path.join(ptuf,"input"+ ext))

        categoryPredict = detect('static/images/input.jpg')
        if len(categoryPredict) > 0:
            croppedDectection = []
            for i in range(len(categoryPredict)):
                croppedDectection.append('images/cropped-dectecion-{}.jpg'.format(i))

            croppedObject = cropped.list_object(zip(categoryPredict, croppedDectection))
        else: 
            croppedObject = None

        objectDetection = 'images/object-detection.jpg'

        return render_template('still.html', f=objectDetection, c=croppedObject)
        
    df = pd.read_csv('static/product-data/top.csv')

    for category in ['dress','shorts','skirt','trousers']:
        df.append(pd.read_csv('static/product-data/{}.csv'.format(category)))

    randomProducts = products.random_products(df, 10)

    return render_template('still.html', r=randomProducts)




@home.route("/recommend", methods=["POST"])
def recommend():

    category = request.args.get('category')
    path = request.args.get('path')

    knn = get_neighbors(category, path)

    df = pd.read_csv('static/product-data/{}.csv'.format(category))

    df = df.iloc[knn[1][0]]

    data = products.list_products(df)

    return render_template("recommend.html", f=path, products = data[:20])

@home.route("/")
def home_page():
    return render_template('index.html')

app/blueprints/upload_api/__init__.py
from .blueprint import upload_api

app/blueprints/upload_api/blueprint.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, send_from_directory, make_response, \
    Response
from werkzeug.utils import secure_filename
import tensorflow as tf
import random
import cv2
import os
import time

from models import products, cropped
from middlewares.yolo import detect
from middlewares.knn import get_neighbors

import re
import base64
import numpy as np

upload_api = Blueprint('upload_api', __name__)

UPLOAD_FOLDER = 'upload'
ALLOWED_EXTENSIONS = {'jpg', 'jpeg'}


# def load_and_preprocess_image(path):
#     '''
#     Read file from path
#     :param path:
#     :return:
#     '''
#     image = tf.io.read_file(path)
#     return preprocess_image(image)

# def generate_img():
#     cap = cv2.VideoCapture(0)

#     cap.set(3, 640)
#     cap.set(4, 480)

#     i = 1

#     while(True):
#         # if button_is_pressed:

#             # Capture frame-by-frame
#         ret, frame = cap.read()
#         i+=1
#         #     img = preprocess_image(frame)
#         #     img = yolov3(img)
#         #     img = img + bounding_boxes
#         #     push new image to canvas of frontend

#         # if i % 20 == 0:
#             # predict = do(frame)
#             # cv2.putText(frame)


#             # return bounding box
#         #     draw on frame 
#         #     have_boundingbox_frame = frame

#         # Display the resulting frame


#         if ret:
#             # flag, jpeg = cv2.imencode('.jpg', have_boundingbox_frame)

#             flag, jpeg = cv2.imencode('.jpg', frame)
#             b = jpeg.tobytes()

#         else:
#             continue
        
#         if flag:

#             yield (b'--frame\r\n'
#                 b'Content-Type: image/jpeg\r\n\r\n' + b + b'\r\n\r\n')

#         else:
#             continue

#         # When everything done, release the capture
#         # cap.release() 
#         # cv2.destroyAllWindows()
    
# @upload_api.route('/video_feed')
# def video_feed():
#     return Response(generate_img(),
#                     mimetype='multipart/x-mixed-replace; boundary=frame')


import uuid

def parse_image(imgData):
    img_str = re.search(b"base64,(.*)", imgData).group(1)
    img_decode = base64.decodebytes(img_str)
    filename = "{}.jpg".format(uuid.uuid4().hex)
    with open('static/images/'+filename, "wb") as f:
        f.write(img_decode)
    return 'static/images/'+filename

# def preprocess(image):
#     image = tf.image.decode_jpeg(image, channels=3)
#     image = tf.image.resize(image, [299, 299])
#     image = image.numpy().reshape((1,299,299,3))
#     image = image/255.0
#     return image

@upload_api.route('/webcam_upload', methods =["POST"])
def webcam_upload():
    data = request.get_json()

    # Preprocess the upload image
    img_raw = data['data-uri'].encode()
    image_path = parse_image(img_raw)
    print(image_path)
    (categoryPredict, positions) = detect(image_path)
    print(categoryPredict)

    if len(categoryPredict) > 0:
        croppedDectection = []
        for i in range(len(categoryPredict)):
            croppedDectection.append('static/images/cropped-dectecion-{}.jpg'.format(i))

        croppedObject = cropped.list_object(zip(categoryPredict, croppedDectection))
    else: 
        croppedDectection = None

    objectDetection = 'static/images/object-detection.jpg'

    os.remove(image_path)

    return {"crop":croppedDectection,"full":objectDetection, "details": positions}
    

    # return {"status":"success"}

app/main.py
from flask import Flask, render_template, redirect, url_for
from blueprints import *
import cv2
import os
from werkzeug.utils import secure_filename

app = Flask(__name__)
app.secret_key = "feij134#$qaf3%QERFAF"  # Flask secret key
app.config["SEND_FILE_MAX_AGE_DEFAULT"] = 0
app.register_blueprint(home)  # blueprint for Home
app.register_blueprint(upload_api)  # blueprint of predicting with model

UPLOAD_FOLDER = 'upload'  # Save images in folder upload
ALLOWED_EXTENSIONS = {'jpg', 'jpeg'}  # Only accept two types of image extension
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=5001, debug=True)



app/models/cropped/__init__.py
from .data_classes import CroppedImage
from .helpers import *

app/models/products/__init__.py
from .data_classes import Product
from .helpers import *

app/templates/base.html
<!doctype html>
<html lang="en" class="has-navbar-fixed-top">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WISH by Nana ❊</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
     integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="static/css/style.css" rel="stylesheet">
    <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
    <link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
    
</head>

<body class="text-center">

<nav class="navbar is-fixed-top has-background-dark navigation">
    <div class="navbar-menu">
        <div class="navbar-start"> 
        <a class="navbar-item has-text-light nav-text" href="/">WISH by Nana</a>
        </div>

        <div class="navbar-end">
            <a class="navbar-item has-text-light nav-text" href="/video"> Shoot </a>
            <a class="navbar-item has-text-light nav-text" href="/still"> Show </a>
        </div>

    </div>
</nav>

{% block content %}
{% endblock %}

<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
<script src="static/js/webcam.js"></script>
<script src="static/js/index.js"></script>
<!-- <script>
    // Add the following code if you want the name of the file appear on select
    $(".custom-file-input").on("change", function () {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
</script> -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/templates/home.html
{% extends "base.html" %}
{% block content %}

<div class="hero-body">

        <div class="container" style="position: relative; padding-left:0;">

            {% if f %}

            <div class="container dec-text">
                <p> Lookin' good!</p>
            </div>

            <img src="{{f}}" class="input-image">

            {% else %}
           
            <img src="{{ url_for('home.videoFeed') }}" class="camera">

            <form action="/video#wish" method="POST" class="wish-camera">
                <button type="submit" class="button is-info is-light" style="margin-left: 30px !important;"> Wish! </button>
            </form>
    
            {% endif %} 

            
        </div>

 

{% if f %}

    {% if c %}
    <div id="wish" class="container" style="margin-bottom: 50px;">
        <div class="tile is-ancester">
        {% for column in [0,1,2] %}
        <div class="tile is-parent is-4 is-vertical">
            <div class="tile is-child"> 
            {% for object in c[column::3] %}
            <div class='recommendation'>
        
            <figure class="image">
                <img class="cropped-image"" src="/static/{{object.path}}" onerror="this.src='static/images/placeholder.jpg'">
            </figure>

            
                <p class="category">{{ object.category }}</p>
            
            
                <form action="{{url_for('home.recommend', category=object.category, path=object.path )}}" method="POST">
                    <button class="button is-info is-light" type="submit">See Recommendations</button>
                </form>
            
            </div>
            <br>
            {% endfor %}
            </div>
        </div>
        {% endfor %}
        </div>
    </div>

    {% else %}
        <h2>Can't detect. Try again.</h2>

    {% endif %}

    <form action="/video"   enctype="multipart/form-data" method="GET">

        <div class="file has-name is-centered">
 
              <button type="submit" class="button is-info back-button" style="margin-left: 30px !important;"> Make another wish! </button>

            </label>
        </div>

    </form>
    
{% endif %}

</div>

  

</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block content %}

<section class="hero is-fullheight-with-navbar">
    <div class="hero-body bg-img">
        <div class="container shoot-show">
            <div class="columns">
              <div class="column is-one-quarter">
                <a class="button is-info is-light shoot-button" href="/video">Shoot</a>
              </div>
              <div class="column is-one-quarter">
                <a class="button is-info is-light show-button" href="/still">Show</a>
              </div>
            </div>
            
          </div>
    </div>
  </section>

{% endblock %}

app/templates/recommend.html
{% extends "base.html" %}
{% block content %}

{% if f %}

<img src="/static/{{f}}" alt="nate" class="input-cropped-image"/>
{% endif %}

<div class="container">
{% for path in c %}
    <img src="/static/{{path}}" alt="nate" class="cropped-image"/>
{% endfor %}
</div>

<div class="container rec-text">
  <p>Wouldn't you look great in these? ♡</p>
</div>


<div class="container">
  
      {% for column in [0,1,2,3,4] %}
      <div class="columns">
        {% for product in products[column::5] %}
        <div class="column"> 

          <div class="container">
              <figure class="image is-2by3">
                <img src="https://{{ product.imageURL }}">
              </figure>

              <div>
                <p class="product-text product-brand">{{ product.brand }}</h3>
              </div>

              <div class="container product-title">
                <p class="product-text">{{ product.name }}</h3>
              </div>

              <div class="columns">
                <div class="column">
                  <p class="product-text price">{{ product.price }}</p>
                </div>

                <div class="column">
                  <a class="button is-info is-light shop-now" target="_blank" href="{{product.hrefs}}"> Shop now!</a>
                </div>

              </div>
          </div>
          <br>
        </div>
        {% endfor %}

        </div>
      {% endfor %}

      </div>

      <div class="container">
        <a class="button is-info back-button" href="/still">Show me something else! ♡</a>
      </div>
     

{% endblock %}

app/templates/still.html
{% extends "base.html" %}
{% block content %}


<div class="hero-body">
  {% if not f %}
  <form action="/still#wish"   enctype="multipart/form-data" method="POST">

        <div class="file has-name is-centered">
            <label class="file-label">
              <input class="file-input" type="file" id="image" name = "uploadfile">
              <span class="file-cta">
                <span class="file-label">
                  Show me anything.
                </span>
              </span>
              <span class="file-name" id="file-name">
                No file chosen.
              </span>
              <button type="submit" class="button is-info is-light" style="margin-left: 30px !important;"> Wish! </button>

            </label>


        </div>
        
  </form>

  <!-- <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">

      <div class="carousel-item active">
        <img class="w-25" src="https://{{r[0].imageURL}}">

        <div class="carousel-caption">
          <h3 class="h3-responsive">Light mask</h3>
          <p>First text</p>
        </div>

      </div>

      {% for product in r[1:] %}
  
      <div class="carousel-item">
        <img class="w-25" src="https://{{ product.imageURL }}">

        <div class="carousel-caption">
          <h3 class="h3-responsive">Light mask</h3>
          <p>First text</p>
        </div>
      </div>


      {% endfor %}
      
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div> -->
  
  {% endif %}

  {% if f %}

  <div class="dec-text">
    <p> Lookin' good!</p>
  </div>

  <img src="/static/{{f}}"/ class="input-image">

    {% if c %}
    <div class="container" id="wish" style="margin-bottom: 50px;">
        <div class="tile is-ancester">
          {% for column in [0,1,2] %}
          <div class="tile is-parent is-4 is-vertical">
            <div class="tile is-child"> 
              {% for object in c[column::3] %}
              <div class='recommendation'>
        
              <figure class="image">
                <img class="cropped-image"" src="/static/{{object.path}}" onerror="this.src='static/images/placeholder.jpg'">
              </figure>
  
            
                <p class="category">{{ object.category }}</p>
              
              
                <form action="{{url_for('home.recommend', category=object.category, path=object.path )}}" method="POST">
                    <button class="button is-info is-light" type="submit">See Recommendations</button>
                </form>
             
              </div>
              <br>
              {% endfor %}
            </div>
          </div>
          {% endfor %}
        </div>
      </div>

      {% else %}
        <h2>Can't detect. Try again.</h2>

      {% endif %}

      <form action="/still"   enctype="multipart/form-data" method="GET">

        <div class="file has-name is-centered">
 
              <button type="submit" class="button is-info back-button" style="margin-left: 30px !important;"> Make another wish! </button>

            </label>
        </div>


  </form>
      
  {% endif %}

</div>
{% endblock %}

app/templates/upload_api.html
{% extends "base.html" %}
{% block content %}
<!-- Your code here -->
{% endblock %}